Api Update for User
coding-blocks/Chatter pull request #134
Opened 2018-07-28 12:31 UTC by aggarwalpulkit596

Fixes #130

Changes:
Changed User Api and JSONObject to JsonArray

2018-07-28 12:32 UTC, aggarwalpulkit596 commented
@the-dagger @championswimmer review this pr

2018-08-02 07:48 UTC, abishekvashok commented on app/src/main/java/com/codingblocks/chatter/DashboardActivity.java
> +                        .url("https://api.gitter.im/v1/user?access_token=" + accessToken)
Please update this btw :P

2018-08-02 07:49 UTC, abishekvashok requested changes

2018-08-02 07:49 UTC, abishekvashok commented on app/src/main/java/com/codingblocks/chatter/DashboardActivity.java
> +                        .url("https://api.gitter.im/v1/user?access_token=" + accessToken)
Update this btw.

2018-08-02 10:09 UTC, aggarwalpulkit596 commented
@championswimmer bhaiya my commit was merged so will i be getting points for this pr?

2018-08-12 13:18 UTC, closed without merging